### ISSUE TITLE
Remove `monkeyPatch`

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk-playground#4]
Removed the proxy with Fetch and Websocket:
- [ ] WebSocket
  - [ ] Preview mode try to initialize comms by WebSocket
  - [ ] Preview mode try to connect to CLI by websocket for hot-reloading
- [ ] Fetch: it seems it can be removed without any inconvenience

**Comment by gonpombo8** [comment]
i can remove this in my refactor 😄 https://github.com/decentraland/sdk-playground/pull/3
